basePath: /
info:
  contact: {}
paths:
  /ping:
    get:
      responses: {}
  /print-task:
    get:
      responses: {}
    patch:
      responses: {}
    post:
      responses: {}
schemes:
- http
swagger: "2.0"
